feat(bouncer): Bug 1710599 Add support to xz linux builds
mozilla-releng/scriptworker-scripts pull request #1082
Opened 2024-10-16 22:53 UTC by hneiva

2024-10-16 23:11 UTC, bhearsum commented
Is this fully decided already? [This most recent comment in the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1710599#c23) suggests that there's still some consideration for zst.

2024-10-17 15:53 UTC, hneiva commented
The final package compression is decided on being xz.
The comment is more around using zst in between tasks for better performance compressing/decompressing. I'm treating that as a potential future improvement, since supporting multiple compression formats would require a lot more work.

2024-10-17 20:28 UTC, bhearsum requested changes
The xz parts look fine here, but please separate the other part out per below.

Also, are beetmoverscript changes needed for this as well (eg: https://github.com/mozilla-releng/scriptworker-scripts/blob/fa61ba745fadd9ce1b1515b09a2deb667805c323/beetmoverscript/src/beetmoverscript/constants.py#L138, https://searchfox.org/mozilla-central/source/taskcluster/gecko_taskgraph/manifests/firefox_candidates.yml, etc.)?

iscript and signingscript also have bz2 references, but I think those are only intermediate packages, and likely don't need any changes.

2024-10-17 20:28 UTC, bhearsum commented on bouncerscript/src/bouncerscript/constants.py
> -        r"^(/firefox/nightly/latest-(mozilla-central|try)/firefox-\d+\.0a1\.en-US\." r"(?:win32\.installer\.msi|win64(?:|-aarch64)\.installer\.msi))$"
Please move the changes like this (and many others further down) that are unrelated to xz support to their own PR. This helps reduces noise here, and ensures that a backout of xz support doesn't back this out, and vice versa.

2024-10-17 21:21 UTC, hneiva commented
I've already added what I needed for signingscript. iscript shouldn't need anything, since this is for linux only.
Still need some fixes for beetmover tho, will add that in a separate PR

2024-10-18 13:13 UTC, bhearsum approved these changes

2024-10-21 16:39 UTC, merged