Add linux-aarch64 to PRODUCT_TO_DESTINATIONS_REGEXES validation in bouncerscript
mozilla-releng/scriptworker-scripts pull request #1101
Opened 2024-12-06 22:14 UTC by gabrielBusta

https://firefox-ci-tc.services.mozilla.com/tasks/OqxKlz8KQAWntEyV74F10w/runs/0/logs/public/logs/live_backing.log

2024-12-09 10:23 UTC, jcristau reviewed
Please track this in bugzilla.

2024-12-09 16:10 UTC, gabrielBusta commented
Ok I will track it on bug [1934634](https://bugzilla.mozilla.org/show_bug.cgi?id=1934634)

2024-12-10 00:08 UTC, bhearsum requested changes
It looks like https://github.com/mozilla-releng/scriptworker-scripts/blob/9ada102afa7ae2180006336f76558dd39f2f90c9/bouncerscript/src/bouncerscript/constants.py#L166 will need an update as well.

2024-12-10 00:11 UTC, hneiva commented
😣 I really want to refactor these gigantic regexes.. Oh well, kick the ball down the road I guess 😁

2024-12-11 02:30 UTC, bhearsum approved these changes
I'm approving, but let's hold off landing until you finish your staging runs, in case they uncover something.

2025-01-09 21:14 UTC, merged