RELENG-587: Add a passwords.yml block for mozillaonline fenix builds
mozilla-releng/scriptworker-scripts pull request #367
Opened 2021-06-08 19:58 UTC by bhearsum

I think this is actually really straightforward? I opened https://github.com/mozilla-services/cloudops-infra/pull/3181 and pushed a sops change for the needed cloudops parts, but AFAICT all we need to do is add the new certs to the mapping here.

There's not much testing to do against dev, because we don't have a special dep cert for mozillaonline.

2021-06-08 20:19 UTC, bhearsum commented
(looks like these failures are mypy related; we'll need some requirements updates to fix them)

2021-06-08 20:38 UTC, escapewindow commented
At least some of the failures are `KeyError: 'AUTOGRAPH_FENIX_MOZILLA_ONLINE_USERNAME'`

2021-06-08 20:40 UTC, escapewindow commented
And yes, the scriptworker_client and iscript failures are mypy related.
I'm not sure if we're getting much of a win from mypy, and I know we're getting a hit in productivity for it. I'm ok with disabling, but I'm also ok with a quick fix.

2021-06-08 20:46 UTC, escapewindow requested changes
Let me know if you have questions?
And agreed, this should be pretty quick once we get the cloudops PR merged.

2021-06-08 20:46 UTC, escapewindow commented on signingscript/docker.d/passwords.yml
> +          - ["https://autograph-external.prod.autograph.services.mozaws.net",
Hm. I think we want to keep this `dep-signing`, and change the format name to, say, `autograph_apk_mozillaonline` or similar.

It's up to us if we actually want to create another format for dep, or just change the taskgraph configs to use `dep-signing` + `autograph_apk` for mozillaonline dep signing?

2021-06-08 20:46 UTC, escapewindow commented on signingscript/docker.d/passwords.yml
> +             ["autograph_apk"]
Same here. We do need a separate set of autograph credentials for mozillaonline, so let's keep the `cert:production-signing`, and add a new `autograph_apk_mozillaonline` or similar format.

2021-06-08 20:49 UTC, escapewindow commented on signingscript/docker.d/passwords.yml
> +             ["autograph_apk"]
(If we did change the cert, we would need to:
- write a ci-config patch to grant the new cert scopes to fenix, and
- update the [CoT restricted scopes](https://github.com/mozilla-releng/scriptworker/blob/master/src/scriptworker/constants.py#L366) to make sure we only use the new production-mozillaonline-signing cert type against the fenix repo)

2021-06-08 20:51 UTC, bhearsum commented on signingscript/docker.d/passwords.yml
> +          - ["https://autograph-external.prod.autograph.services.mozaws.net",
I don't see any reason to use a new cert for dep signing. Is there a reason we need to change the scope name, if we're using the same cert?

2021-06-08 20:54 UTC, bhearsum commented on signingscript/docker.d/passwords.yml
> +             ["autograph_apk"]
It sounds like you're saying the reason we need to use the existing certs is to satisfy CoT? If so, that makes sense. (I couldn't find any reason within `signingscript` to require it.)

2021-06-08 20:55 UTC, escapewindow commented on signingscript/docker.d/passwords.yml
> +          - ["https://autograph-external.prod.autograph.services.mozaws.net",
Nope. Maybe just json-e in the signing kind: for depsigning, use `dep-signing` + `autograph_apk` format; if we're release signing, use `production-signing` + `autograph_apk_mozillaonline` or similar.

2021-06-08 20:57 UTC, escapewindow commented on signingscript/docker.d/passwords.yml
> +             ["autograph_apk"]
It's mainly for separating out scopes and yes, restricting certain cert scopes to certain repos in CoT. Formats are, I think, just in the upstreamArtifacts and are no longer scopes at all.

2021-06-08 20:57 UTC, bhearsum commented on signingscript/docker.d/passwords.yml
> +          - ["https://autograph-external.prod.autograph.services.mozaws.net",
sgtm; thanks for the pointers.

2021-06-09 16:53 UTC, escapewindow approved these changes
LGTM, thank you!

I think we can roll these out at any point.

2021-06-09 18:05 UTC, merged