upgrade python environment to 3.9, remove 3.7
mozilla-releng/scriptworker-scripts pull request #428
Opened 2021-10-21 15:57 UTC by jmaher

…r 3.10

2021-10-21 18:30 UTC, escapewindow reviewed
Not sure what's going to happen to these review comments...

2021-10-21 18:30 UTC, escapewindow commented on addonscript/Dockerfile
> +FROM python:3.10.0
I don't love that we're hardcoding this here, though this may be the best case until we resolve #372.
The canonical way would be e.g. to [set PYTHON_VERSION](https://github.com/mozilla-releng/scriptworker-scripts/blob/master/taskcluster/ci/docker-image/kind.yml#L19) and [parent](https://github.com/mozilla-releng/scriptworker-scripts/blob/master/taskcluster/ci/docker-image/kind.yml#L26) and using

```
ARG DOCKER_IMAGE_PARENT
FROM $DOCKER_IMAGE_PARENT
```

like we do in e.g. [pushsnapscript](https://github.com/mozilla-releng/scriptworker-scripts/blob/master/taskcluster/docker/pushsnapscript/Dockerfile), but I'm not 100% sure if that's tied into the k8s-image task kind.

We should probably hardcode whatever version of python we're running in prod for each one, so I'm guessing that would be either a version of python3.8 or a python3.9. (Be aware that if we upgrade the entire set of scriptworkers to python 3.9 now, there will be more testing than just signingscript.) We may want to push all of these changes to `dev` and run a `dev` staging release at the end of this :)

2021-10-21 18:30 UTC, escapewindow commented on addonscript/requirements/base.py37.txt
> -# SHA1:c2cac962ccf2991d069e31c6e916c06a77d42985
If we're removing py37 support, we can probably remove [importlib-metadata](https://github.com/mozilla-releng/scriptworker-scripts/blob/master/addonscript/requirements/base.in#L4-L6).

2021-10-21 18:30 UTC, escapewindow commented on addonscript/pyproject.toml
> +target-version = ["py38", "py39", "py310"]
guessing we're going to remove py310 for now.

2021-10-21 18:36 UTC, escapewindow reviewed
Nice, this is looking good, thank you!

2021-10-21 18:36 UTC, escapewindow commented on addonscript/requirements/base.txt
>      --hash=sha256:07a6becac60f6cd2604b9f2b73bcd9a50079a0b7b55e2a4e45b1eec5a3ea9659 \
I'd love for all the .txt files to have the py3x as part of the name for consistency, but that doesn't have to happen in this PR.

An observation that doesn't require action: our requirements.txt files are the same!
The local and test files are different. I wonder if that means we can someday get down to one set of requirements files though.

```
43500 37 base.py38.txt
43500 37 base.txt
58672 2 local.py38.txt
28338 2 local.txt
40641 14 test.py38.txt
36194 14 test.txt
```

2021-10-21 18:36 UTC, escapewindow commented on addonscript/tox.ini
> +depends = py39
We probably want to also update the top level [tox.ini](https://github.com/mozilla-releng/scriptworker-scripts/blob/master/tox.ini#L51) to move the `check` target to the py39 (or whatever is the shipping python minor version) per script as well.

2021-10-22 15:02 UTC, jmaher commented on addonscript/requirements/base.txt
>      --hash=sha256:07a6becac60f6cd2604b9f2b73bcd9a50079a0b7b55e2a4e45b1eec5a3ea9659 \
I tried this out, it seemed possible until I got to `pip-compile-multi verify`.  Here is it expecting base.in -> base.txt, and there is no option to specify the outfile, it is derived from the .in script.

2021-10-22 15:03 UTC, jmaher commented on addonscript/pyproject.toml
> +target-version = ["py38", "py39", "py310"]
yeah, 310 is not supported in black, a bit too early.

2021-10-22 15:06 UTC, jmaher commented on addonscript/Dockerfile
> +FROM python:3.10.0
I thought I could do this and fiddled around a lot with this- in the end we are running docker 1.6.2 for the k8s-images, and in order for the ability to pass in --build-arg <ARG>, we need docker 1.9.  For our test images used in tox, etc. we are ok and that is why there is prior art in the repo with PYTHON_VERSION, etc.

2021-10-22 21:14 UTC, jmaher commented on addonscript/tox.ini
> +depends = py39
thanks for mentioning this- my latest changes have this!

2021-10-26 00:36 UTC, escapewindow requested changes
Wow!

First of all, thank you! Amazing work.
Second, it looks like the tests are green here. I have a couple questions and comments in the review. Mostly minor; I'm wondering about the py suffix comment; I'm happy to r+ once we verify what that should be.

Third, how do you want to roll out? I could see:
- wait until after we ship 94? next week, then YOLO out to `production`, and debug everything. There's a chance we'll have to scramble and fix something or back out.
- push to `dev` before rolling out, and run a staging release using all dev scriptworkers. This won't catch everything, but it'll catch at least some issues. This is more yak shaving, but we'll have more confidence when we roll out.
-  roll out to `production-*` one by one as time allows. We could combine this with the staging release option above for even more confidence. The staging release + rolling out one by one is probably the slowest calendar-time wise, but has the highest chance of catching issues.

Do any of those appeal to you more? I'm open to helping you with any of those.

Either way, we probably want to communicate with the team and #releaseduty about these rollouts, and we may want to resurrect the [releng changelog](https://docs.mozilla-releng.net/en/latest/releng_changelog.html) to note when we upgraded the scriptworkers to py39 in case we need to debug things later.

2021-10-26 00:36 UTC, escapewindow commented on addonscript/README.rst
> +--------------------------
Looks like we could duplicate this doc in a lot of places -- maybe link to a top level README.rst?
Non-blocking.

2021-10-26 00:36 UTC, escapewindow commented on addonscript/requirements/base.txt
> +cryptography==35.0.0 \
I'm kind of leaning towards landing these changes post-mergeday next week, so we can YOLO a little bit.

2021-10-26 00:36 UTC, escapewindow commented on iscript/README.md
> +The easiest way to do this is to run `pin.sh`:
This is actually inaccurate for rolling out dependency updates to production iscript and `notarization_poller`. For these two, we use the script / requirements files [here](https://github.com/mozilla-platform-ops/ronin_puppet/tree/master/modules/signing_worker/files), and the `scriptworker{,_scripts}_revision` [here](https://github.com/mozilla-platform-ops/ronin_puppet/blob/master/data/common.yaml#L125-L143). And I believe we'll keep using python 3.8 for these two for the time being (this is due to the python that's baked into the mac puppet configs, not anything you need to change here).

If you want to update these two READMEs to be accurate, that would be awesome, otherwise we're not any more inaccurate than we were before :)

2021-10-26 00:36 UTC, escapewindow commented on pushsnapscript/Dockerfile
> +FROM python:3.9.7
One of these push* scripts may have some tricky bits with which OS version we use. I'm not sure which one, and these are trickier to test because of the external stores. I'm hoping it's pushsnap, because we're going to [EOL it](https://mozilla-hub.atlassian.net/browse/RELENG-688).

2021-10-26 00:36 UTC, escapewindow commented on taskcluster/ci/docker-image/kind.yml
> +            PYTHON_REQ_SUFFIX: ".py39"
Hm, is this right? I see base.txt not base.py39.txt ?

2021-10-26 21:35 UTC, jmaher commented on addonscript/README.rst
> +--------------------------
we have this in the top level doc, I would like to update each doc with some testing notes as well, maybe I will save this cleanup for docs later this week.

2021-10-26 21:36 UTC, jmaher commented on iscript/README.md
> +The easiest way to do this is to run `pin.sh`:
fixed this!

2021-10-26 23:35 UTC, escapewindow commented on iscript/pyproject.toml
> +target-version = ["py38"]
Ah, it might be nice to test py39 in iscript even if we don't upgrade yet :)

2021-10-26 23:39 UTC, escapewindow commented
The changes look good, though I do wish we could have kept the iscript/notarization_poller py39 tests, just updating the readme to note that we're still on py38 until we upgrade ronin-puppet.

Even though you force-pushed, you can see the diff via something like `git diff 3607de643637d9b2706ab1b83719a09009f2f083 bd2fafe7afe45440eca0cdd6a715066d065890bf`. You can find those revisions above in this PR, or in the reflog, e.g. `.git/logs/refs/remotes/jmaher/py39` (your remote may be named something other than `jmaher`, maybe `origin`)

2021-10-27 15:42 UTC, jmaher commented on iscript/pyproject.toml
> +target-version = ["py38"]
done!

2021-10-27 15:42 UTC, jmaher commented on taskcluster/ci/docker-image/kind.yml
> +            PYTHON_REQ_SUFFIX: ".py39"
good catch, I fixed that

2021-10-27 19:45 UTC, escapewindow reviewed
The latest diff (`git diff bd2fafe7 1f2e8d71`) looks good except for the spots I commented, thank you!

Do you want help testing on dev, or are you set?

2021-10-27 19:45 UTC, escapewindow commented on iscript/tox.ini
> +#    docker build --build-arg PYTHON_VERSION=3.9.7 --build-arg PYTHON_REQ_SUFFIX=.py39 -t iscript-{envname}-py39-test -f Dockerfile.test .
Looks like we have PYTHON_REQ_SUFFIX=.py39 again :)

2021-10-27 19:45 UTC, escapewindow commented on tox.ini
> +#[testenv:iscript-py39]
Do we want to uncomment this?

2021-10-27 19:50 UTC, jmaher commented on tox.ini
> +#[testenv:iscript-py39]
no, there is an issue with plistlib:
plist removed: https://docs.python.org/3.9/whatsnew/3.9.html#removed
we see the failure failure:
```
 E           AttributeError: <module 'plistlib' from '/usr/local/lib/python3.9/plistlib.py'> does not have the attribute 'readPlist'
```
/usr/local/lib/python3.9/unittest/mock.py:1378: AttributeError

2021-10-27 19:50 UTC, jmaher commented on iscript/tox.ini
> +#    docker build --build-arg PYTHON_VERSION=3.9.7 --build-arg PYTHON_REQ_SUFFIX=.py39 -t iscript-{envname}-py39-test -f Dockerfile.test .
yes, that is for iscript, I left it in on purpose this time.

2021-10-27 20:26 UTC, escapewindow commented on iscript/tox.ini
> +#    docker build --build-arg PYTHON_VERSION=3.9.7 --build-arg PYTHON_REQ_SUFFIX=.py39 -t iscript-{envname}-py39-test -f Dockerfile.test .
Ok. I'll go ahead and approve, and whatever we have left that needs fixing up we can do in followup PRs.
Let's not land this til after we ship 94.0, though.

2021-10-27 20:27 UTC, escapewindow approved these changes

2021-11-03 18:59 UTC, merged