[VPN] Use local provisionprofile instead of URL
mozilla-releng/scriptworker-scripts pull request #487
Opened 2022-03-10 21:29 UTC by hneiva

2022-03-10 21:42 UTC, ahal requested changes
I think we should remove the `download_provisioning_profile` function as well? Or do you think we'll use that for other projects?

Otherwise LGTM!

2022-03-10 21:42 UTC, ahal commented on iscript/src/iscript/macvpn.py
> +    if config.get("provisionprofile_folder"):
nit: `provisionprofile_dir`?

2022-03-10 21:42 UTC, ahal commented on iscript/src/iscript/macvpn.py
> +        provisioning_profile_path = os.path.join(config.get("provisionprofile_folder"), provisionprofile_filename)
nit: don't need to use `config.get` here

2022-03-10 21:43 UTC, ahal commented on iscript/src/iscript/macvpn.py
> +            raise IScriptError("Something")
Did you mean to update this to something more informative? :)

2022-03-10 22:19 UTC, ahal approved these changes
Thanks!

2022-03-11 16:30 UTC, hneiva commented
> I think we should remove the `download_provisioning_profile` function as well? Or do you think we'll use that for other projects?
> 
> Otherwise LGTM!

I'll write a ticket for it so we can check with gecko/other products.

2022-03-11 16:30 UTC, merged