Google cloud artifact registry support for beetmoverscript
mozilla-releng/scriptworker-scripts pull request #578
Opened 2022-10-26 21:01 UTC by gabrielBusta

`task.json` (`sources` supports wildcards)
```
{
  "provisionerId": "scriptworker-k8s",
  "workerType": "gecko-3-beetmover",
  "taskQueueId": "scriptworker-k8s/gecko-3-beetmover",
  "schedulerId": "gecko-level-3",
  "projectId": "none",
  "taskGroupId": "dyj0PA0MSk6ka3KLIQMnwQ",
  "dependencies": ["cLhmqc95SFisEdFpKBdNlg", "IP1F48mGQb-DwOZq3iN-EA"],
  "requires": "all-completed",
  "routes": ["checks"],
  "priority": "low",
  "retries": 5,
  "created": "2022-08-08T22:48:42.512Z",
  "deadline": "2022-08-09T22:48:42.512Z",
  "expires": "2023-08-08T22:48:42.512Z",
  "scopes": [
    "project:releng:beetmover:apt-repo:moz-fx-dev-releng",
    "project:releng:beetmover:action:import-artifacts"
  ],
  "payload": {
    "maxRunTime": 600,
    "sources": [
      "pub/firefox/nightly/latest-mozilla-central-l10n/target.deb"
    ],
    "releaseProperties": {
      "branch": "mozilla-central",
      "appName": "Firefox",
      "buildid": "20221026034746",
      "hashType": "sha512",
      "platform": "linux64",
      "appVersion": "108.0a1"
    }
  },
  "extra": {
    "index": {
      "rank": 0
    },
    "parent": "IP1F48mGQb-DwOZq3iN-EA"
  }
}
```
`local.log`
```
2022-10-26 15:50:20,528 - beetmoverscript.task - INFO - Action types: ['import-artifacts']
2022-10-26 15:50:20,803 - beetmoverscript.gcloud - INFO - name: "projects/moz-fx-dev-releng/locations/northamerica-northeast2/repositories/releng-apt-dev"
format_: APT
create_time {
  seconds: 1655412233
  nanos: 853353000
}
update_time {
  seconds: 1655412233
  nanos: 853353000
}

2022-10-26 15:50:20,803 - beetmoverscript.gcloud - INFO - uris: "gs://releng-beetmover-dev/pub/firefox/nightly/latest-mozilla-central-l10n/target.deb"
use_wildcards: true

2022-10-26 15:50:20,803 - beetmoverscript.gcloud - INFO - gcs_source {
  uris: "gs://releng-beetmover-dev/pub/firefox/nightly/latest-mozilla-central-l10n/target.deb"
  use_wildcards: true
}
parent: "projects/moz-fx-dev-releng/locations/northamerica-northeast2/repositories/releng-apt-dev"

2022-10-26 15:50:29,165 - beetmoverscript.gcloud - INFO - apt_artifacts {
  name: "projects/moz-fx-dev-releng/locations/northamerica-northeast2/repositories/releng-apt-dev/aptArtifacts/pool%2Ffirefox-default_107.0a1.20221013200732_amd64_817a7fc8976a85c930ef069ee295187d.deb"
  package_name: "firefox-default"
  package_type: BINARY
  architecture: "amd64"
  component: "main"
}

2022-10-26 15:50:29,166 - beetmoverscript.script - INFO - Success!
```

2023-01-27 21:56 UTC, gabrielBusta commented on beetmoverscript/src/beetmoverscript/gcloud.py
> +    project = "moz-fx-dev-releng"  # the project the repo is in. hard-coding our dev. env. for now
ah I forgot about this, this needs some work

2023-01-27 21:58 UTC, gabrielBusta commented on beetmoverscript/src/beetmoverscript/gcloud.py
> +    product = get_product_name(context.task, context.config)
Ah I forgot I hard-coded the GCP project and location, this needs some work

2023-01-27 21:58 UTC, gabrielBusta commented on beetmoverscript/src/beetmoverscript/gcloud.py
> +    location = "northamerica-northeast2"  # this is the region / location of the repo. got it from the console
Ah I forgot I hard-coded the GCP `project` and `location`, this needs some work

2023-02-09 17:50 UTC, gabrielBusta commented on beetmoverscript/docker.d/init_worker.sh
> +        test_var_set 'PROJECT_NAME'
more details about this env var [here](https://mozilla-hub.atlassian.net/browse/SVCSE-1067)

2023-02-09 18:03 UTC, gabrielBusta commented on beetmoverscript/docker.d/init_worker.sh
> +        test_var_set 'PROJECT_NAME'
This is not what I thought... looked in the `configmap` and the value is `beetmover`

2023-03-14 17:36 UTC, hneiva requested changes

2023-03-14 17:36 UTC, hneiva commented on beetmoverscript/requirements/base.in
> +google-cloud-artifact-registry
```suggestion
google-cloud-artifact-registry

```
Missing empty line at EOF

2023-03-14 17:36 UTC, hneiva commented on beetmoverscript/src/beetmoverscript/gcloud.py
> +        context.gcp_client = _get_gcs_client(context, product)
`gcp_client` has very different methods when dealing with the different services.  `context` is bad enough as a god object, and we made this mistake with "bucket name" property already.

I suggest we split it into `gcs_client` and `gar_client` (or something of the sorts).

```suggestion
        context.gar_client = _get_artifact_registry_client(context, product)
        ....
        context.gcs_client = _get_gcs_client(context, product)
```

2023-03-14 17:36 UTC, hneiva commented on beetmoverscript/src/beetmoverscript/gcloud.py
> +    if "repo" in context.resource_type:
```suggestion
    if context.resource_type in ("yum-repo", "apt-repo"):
```

2023-03-14 17:36 UTC, hneiva commented on beetmoverscript/src/beetmoverscript/gcloud.py
> +    # artifact registry supports docker... interesting...
```suggestion
```

2023-03-14 17:36 UTC, hneiva commented on beetmoverscript/src/beetmoverscript/task.py
> +    """Extract task cloud resource from scopes"""
Please add an explanation of what "resource" is in this context.

Also: Thank you for renaming this. It was VERY confusing.

2023-03-14 17:36 UTC, hneiva commented on beetmoverscript/src/beetmoverscript/utils.py
> +    if action == "push-to-releases" or action == "import-from-gcs-to-artifact-registry":
```suggestion
    if action in ("push-to-releases", "import-from-gcs-to-artifact-registry"):
```

2023-03-14 17:36 UTC, hneiva commented on beetmoverscript/src/beetmoverscript/gcloud.py
> +    async_operation = await do_artifact_registry_import_artifacts_request(context, import_artifacts_request)
Looking at `build_artifact_registry_import_artifacts_request`, `build_artifact_registry_gcs_source` and `do_artifact_registry_import_artifacts_request`, makes me wish we were more object-oriented (with classes).
All 3 functions are switching on the same flag, and "doing more than one thing".

One way of simplifying  the logic would be to have the switching in `import_from_gcs_to_artifact_registry`
```
if context.resource_type == "apt-repo":
    result = import_apt(....)
elif context.resource_type == "yum-repo":
    result = import_yum(...)
else:
    raise Exception("Artifact Registry resource must be one of [apt-repo, yum-repo]")
```

2023-03-22 15:44 UTC, gabrielBusta commented
[Here is a try push beetmovin' the langpacks and the binary.](https://treeherder.mozilla.org/jobs?repo=try&revision=5d522f7c362cf62abcb83e052df80f78892c1566)

These are `beetmover-apt` tasks [1](https://firefox-ci-tc.services.mozilla.com/tasks/VsNJ2I1DRYGg0OfTuyJQag), [2](https://firefox-ci-tc.services.mozilla.com/tasks/elRI4ehrSimfpabymm88AQ), and [3](https://firefox-ci-tc.services.mozilla.com/tasks/UQ93sT7YS_SN360FFhuhyA).

[Here is a staging beta beetmovin' the langpacks and the binary.](https://treeherder.mozilla.org/jobs?repo=try&revision=a72e7b08483db074c63f0d8c47730755465b0d66)

This is the [beta's beetmover-apt task](https://firefox-ci-tc.services.mozilla.com/tasks/LeYgYtgzQ-ih8SwGqt_Faw) (the staging release only generates a subset of the langpacks)

2023-03-27 19:23 UTC, hneiva approved these changes

2023-03-27 19:24 UTC, merged