[ci] Upgrade to taskgraph 4.1.1
mozilla-releng/scriptworker-scripts pull request #667
Opened 2023-02-15 22:24 UTC by hneiva

2023-02-16 10:00 UTC, jcristau commented
Missing an update to `taskcluster/requirements.*`?  Looks like this is still using 1.1.7 (and so not creating any tasks).

2023-02-22 10:06 UTC, jcristau requested changes

2023-02-22 10:06 UTC, jcristau commented on taskcluster/requirements.txt
> +taskcluster-taskgraph==4.1.1 \
Let's also version the dependency in requirements.in, for documentation purposes if nothing else.  The incompatible changes mean we need at least 3.x.

2023-02-22 10:06 UTC, jcristau commented on taskcluster/scriptworker_taskgraph/transforms/python_version.py
> +        task = deepcopy(task_raw)
Moving the deepcopy outside the loop doesn't seem safe.  AFAICT `_resolve_replace_string` would end up making changes to `task` in the first iteration that persist for later ones.
E.g. https://firefox-ci-tc.services.mozilla.com/tasks/NW_4tQxDSLqsr28eOp1azg is supposed to be using python 3.9 but ends up with 3.8.

2023-02-22 10:06 UTC, jcristau commented on taskcluster/scriptworker_taskgraph/transforms/python_version.py
> +        task = deepcopy(task_raw)
Why copy?

2023-02-28 21:29 UTC, hneiva commented
I just realized I never merged this.
@ahal should we upgrade to 4.2.0 instead?

2023-03-02 15:55 UTC, ahal commented
Up to you, doesn't hurt I suppose.

2023-03-03 15:27 UTC, ahal approved these changes
Thanks, lgtm!

2023-03-08 22:08 UTC, gabrielBusta approved these changes

2023-03-10 21:49 UTC, merged