Bug 1842229 - APK creds cleanup and add stage autograph
mozilla-releng/scriptworker-scripts pull request #833
Opened 2023-08-04 14:22 UTC by JohanLorenzo

Depends on https://github.com/mozilla-services/cloudops-infra/pull/5012

2023-08-04 14:33 UTC, ahal requested changes

2023-08-04 14:33 UTC, ahal commented on signingscript/docker.d/passwords.yml
> +            ]
I think the plan was to set this up against adhoc right?

2023-08-04 14:45 UTC, ahal commented on signingscript/docker.d/passwords.yml
> +            ]
I recall our conversation about setting it up in both places now, but you'll still need to add this for adhoc.

2023-08-04 15:16 UTC, JohanLorenzo commented on signingscript/docker.d/passwords.yml
> +            ]
My bad, I though adhoc signing was covered in this block but I realized it has its own section below. Done!

2023-08-04 15:28 UTC, ahal requested changes
Thanks!

There are some test failures. The `test_init.py` ones are because you need to add the new variables to:
https://github.com/mozilla-releng/scriptworker-scripts/blob/master/tests/test_init.py#L79

2023-08-04 15:28 UTC, ahal commented on signingscript/docker.d/init_worker.sh
> +        test_var_set 'AUTOGRAPH_FENIX_STAGE_USERNAME'
This will need to be changed to `AUTOGRAPH_STAGE_FENIX_PASSWORD` etc as well now.

2023-08-04 18:02 UTC, JohanLorenzo commented
All test failures are now fixed!

2023-08-07 10:11 UTC, JohanLorenzo commented
New creds were tested in https://github.com/mozilla-mobile/firefox-android/pull/2886 and more precisely with these tasks: 

* https://firefox-ci-tc.services.mozilla.com/tasks/ZDlCZbbTSl-MD-UUc8MZjg
* https://firefox-ci-tc.services.mozilla.com/tasks/UR7yWcAyRTOcs_T9TU8gTg

I think we're good to proceed get this merged. Let's put this in today to get signing_script deployment stabilized. r? @gabrielBusta

2023-08-07 15:06 UTC, gabrielBusta approved these changes

2023-08-07 15:06 UTC, gabrielBusta commented
Thanks for testing it

2023-08-07 15:13 UTC, merged